from flask import Flask, render_template, url_for

app = Flask(__name__)

db = {
  "posts": [
    {
      "id": 1,
      "userId": 1,
      "title": "HTMX is awesome!",
      "content": "I just learned about HTMX and it's awesome!",
      "comments": [1, 2]
    },
    {
      "id": 2,
      "userId": 1,
      "title": "This post is generated by ChatGPT",
      "content": "I'm a robot. I'm writing this post using ChatGPT.",
      "comments": [3]
    },
    {
      "id": 3,
      "userId": 2,
      "title": "I'm tired...",
      "content": "It's 3am and I want to sleep.",
      "comments": []
    }
  ]
}

@app.route("/")
def home():
    return render_template("home/index.html", db=db)

@app.route("/posts")
def posts():
    return render_template("posts/index.html", db=db)